version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
    overwrite: yes
 
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    
hooks:
  AfterInstall:
    - location: after-deploy.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: server-start.sh
      timeout: 60
      runas: root
    
# hooks:
#   BeforeInstall:
#     - Location: /after-deploy.sh
#       timeout: 60
#       runas: ubuntu
#   AfterInstall:
#     - Location: /before-deploy.sh
#       timeout: 60
#       runas: ubuntu
