version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/
    overwirte: yes
file_exists_behavior: OVERWRITE
  
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    
hooks:
  AfterInstall:
    - Location: deploy.sh
      timeout: 60
      runas: ubuntu
