# Generated by Django 4.2 on 2023-05-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_remove_diary_user_id_diary_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="diary_img_id",
        ),
        migrations.AddField(
            model_name="diaryimg",
            name="diary_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="diary.diary"
            ),
        ),
    ]
