# Generated by Django 4.2 on 2023-05-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_remove_diary_diary_img_id_diaryimg_diary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryimg",
            name="diary_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diary.diary"
            ),
        ),
        migrations.AlterField(
            model_name="diaryimg",
            name="thumbnail_url",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="diaryimg",
            name="url",
            field=models.TextField(null=True),
        ),
    ]
