# Generated by Django 4.2 on 2023-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_alter_diaryimg_diary_id_alter_diaryimg_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="title",
        ),
        migrations.AddField(
            model_name="diary",
            name="date",
            field=models.DateField(default="2023-05-21"),
            preserve_default=False,
        ),
    ]
