# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout release
        uses: actions/checkout@v2

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name sketchday-app
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name sketchday-deploy-group
